FROM openjdk:11
ADD target/ClaimsPensionMicroservice-0.0.1-SNAPSHOT.jar ClaimsPensionMicroservice-0.0.1-SNAPSHOT.jar
EXPOSE 9002
ENTRYPOINT ["java", "-jar" , "ClaimsPensionMicroservice-0.0.1-SNAPSHOT.jar"]