
server:
  port: 9000
  


spring:
  application:
    name: Pensioner-Api-Gateway
  cloud:
    gateway:
      routes:
      - id: authorization-microservice
        uri: http://172.26.80.1:9001/
        predicates:
        - Path=/login/** 
      - id: process-pension-microservice
        uri: http://172.26.80.1:9002/
        predicates:
        - Path=/claims/**
      - id: pensioner-details-service
        uri: http://172.26.80.1:9003/
        predicates:
        - Path=/details/**
        
      
        
      
        
          
