FROM openjdk:11
ADD target/AuthorizationMicroservice-0.0.1-SNAPSHOT.jar AuthorizationMicroservice-0.0.1-SNAPSHOT.jar
EXPOSE 9001
ENTRYPOINT ["java", "-jar" , "AuthorizationMicroservice-0.0.1-SNAPSHOT.jar"]